### ISSUE TITLE
fzaninotto/faker  is abondoned. 

### ISSUE THREAD

**Issue by blafasel42** [ComPHPPuebla/dbal-fixtures#10]
dependency faker seems not to be under development anymore. 

maybe switch to https://github.com/fakerphp/faker ?

**Comment by blafasel42** [comment]
this is quite easy. see my fork at https://github.com/100DAYS/dbal-fixtures/blob/c45b3cb94ef39d0781b2ba21547a11c965340b53/composer.json#L17

**Comment by MontealegreLuis** [comment]
Fixed in #9
