### ISSUE TITLE
packagist version outdated

### ISSUE THREAD

**Issue by blafasel42** [ComPHPPuebla/dbal-fixtures#2]
Hi, thanks for sharing this. unfortunately, the latest changes in this repo were not pushed to packagist. this includes support for null-values...

**Comment by MontealegreLuis** [comment]
Hi @blafasel42 I created a new [release](https://github.com/ComPHPPuebla/dbal-fixtures/releases/tag/3.1.0) including those changes. There's still room to improve the documentation, I'll try to find some time soon. I appreciate any feedback you can give us for this package.
