### ISSUE TITLE
Bump version of symfony in 4.x

### ISSUE THREAD

**Issue by ektarum** [ComPHPPuebla/dbal-fixtures#5]
Hi !

the version of symfony package is lock in 3.x .

Can you make new version with 4.x version ?

Thanks in advance

**Comment by MontealegreLuis** [comment]
Hi @ektarum !

I've just released [4.0.0](https://packagist.org/packages/comphppuebla/dbal-fixtures) with that update.

**Comment by ektarum** [comment]
great news ! thanks to you.
