### ISSUE TITLE
lastinsertId not working if id field is in the data

### ISSUE THREAD

**Issue by blafasel42** [ComPHPPuebla/dbal-fixtures#6]
Hi, i use this lib for a small project and it works fine.
BUT:

At least in postgres driver (but probably in some others, too), when a record is inserted and the record did contain the id field, PDO will not return a lastInsertId(), i.e. the returned id will be 0.

Sometimes this even results in a an error like "sequence value not initialized for this session"

https://github.com/ComPHPPuebla/dbal-fixtures/blob/6607fc8dcefc82cfe9c3c553b86c92cc26893991/src/Database/DBALConnection.php#L24

**Comment by MontealegreLuis** [comment]
Hi @blafasel42 could you please help me 2 things? 

1. The entry in your `.yml` file that produces this error, and 
2. The create statement of your table so I can add some integration tests to fix this issue

Thank you!

**Comment by blafasel42** [comment]
seems like this has been solved in DBAL now...
